export const expenseCategories = [
    {
        id: "Food",
        label: "Food",
        icon: { name: "utensils", type: "FontAwesome5" },
        bgColor: "#FFE5E0",
        iconColor: "#FF5733",
    },
    {
        id: "transport",
        label: "Transport",
        icon: { name: "bus", type: "FontAwesome5" },
        bgColor: "#E0F7FA",
        iconColor: "#0097A7",
    },
    {
        id: "shopping",
        label: "Shopping",
        icon: { name: "shopping-bag", type: "FontAwesome5" },
        bgColor: "#FFF3E0",
        iconColor: "#FB8C00",
    },
    {
        id: "entertainment",
        label: "Entertainment",
        icon: { name: "film", type: "FontAwesome5" },
        bgColor: "#EDE7F6",
        iconColor: "#5E35B1",
    },
    {
        id: "bills",
        label: "Bills & Utilities",
        icon: { name: "file-invoice-dollar", type: "FontAwesome5" },
        bgColor: "#F1F8E9",
        iconColor: "#689F38",
    },
    {
        id: "groceries",
        label: "Groceries",
        icon: { name: "shopping-cart", type: "FontAwesome5" },
        bgColor: "#FFFDE7",
        iconColor: "#FBC02D",
    },
    {
        id: "health",
        label: "Health",
        icon: { name: "heartbeat", type: "FontAwesome5" },
        bgColor: "#FCE4EC",
        iconColor: "#D81B60",
    },
    {
        id: "education",
        label: "Education",
        icon: { name: "book", type: "FontAwesome5" },
        bgColor: "#E3F2FD",
        iconColor: "#1976D2",
    },
    {
        id: "travel",
        label: "Travel",
        icon: { name: "plane", type: "FontAwesome5" },
        bgColor: "#E0F2F1",
        iconColor: "#00796B",
    },
    {
        id: "subscriptions",
        label: "Subscriptions",
        icon: { name: "play-circle", type: "FontAwesome5" },
        bgColor: "#F9FBE7",
        iconColor: "#AFB42B",
    },
    {
        id: "salary",
        label: "Salary",
        icon: { name: "wallet", type: "FontAwesome5" },
        bgColor: "#E8F5E9",
        iconColor: "#2E7D32",
    },
    {
        id: "others",
        label: "Others",
        icon: { name: "ellipsis-h", type: "FontAwesome5" },
        bgColor: "#ECEFF1",
        iconColor: "#546E7A",
    },
];
